on:
  push:
    branches:
      - main
      - 2.1.x
  workflow_dispatch:
name: Build
jobs:
  make:
    name: Build and Upload Sileo
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install ldid and dpkg
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install ldid dpkg
      - name: Build Sileo Nightly
        run: |
         make clean package NIGHTLY=1 DEBUG=0
      - name: Upload To Repo
        id: upload
        run: |
          package=$(ls -t packages | head -1)
          echo "::set-output name=PACKAGE_PATH::$package"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          # Artifact name
          name: Sileo # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./packages/${{ steps.upload.outputs.PACKAGE_PATH }}
  lint:
    name: Lint Sileo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app 
      - name: Run Tests
        run: xcodebuild test -scheme "Sileo Demo" -project Sileo.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
